"""Agregar direccion, latitud y longitud a Evento

Revision ID: 7e399c5c6695
Revises: 876c5c2b3943
Create Date: 2025-06-04 15:08:24.670677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e399c5c6695'
down_revision = '876c5c2b3943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.alter_column('ubicacion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
